title: Brandon and Elisabeth
description: London Wedding 2027-07-27
domain: morolee.life
url: https://bleecr7.github.io
baseurl: /wedding-page

collections:
  sections:
    output: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

timezone: Europe/London
